name: fish format check

on:
  workflow_call:

jobs:
  fish_format:
    name: fish format check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install fish
        uses: fish-actions/install-fish@v1

      - name: Check fish files
        uses: fish-actions/format-check@v1
